"""init_all_tables

Revision ID: 494e66f7a6a4
Revises: 
Create Date: 2026-06-26 10:40:48.280941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '494e66f7a6a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_record',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stream_url', sa.Text(), nullable=False),
    sa.Column('stream_id', sa.String(length=64), nullable=True),
    sa.Column('alarm_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('class_name', sa.String(length=64), nullable=True),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('create_by', sa.String(length=64), nullable=True),
    sa.Column('update_by', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotation_box',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=64), nullable=False),
    sa.Column('cx', sa.Float(), nullable=False),
    sa.Column('cy', sa.Float(), nullable=False),
    sa.Column('bw', sa.Float(), nullable=False),
    sa.Column('bh', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('annotator', sa.String(length=64), nullable=True),
    sa.Column('create_by', sa.String(length=64), nullable=True),
    sa.Column('update_by', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotation_box', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_box_image_id'), ['image_id'], unique=False)

    op.create_table('annotation_image',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('dataset_name', sa.String(length=128), nullable=True),
    sa.Column('split', sa.String(length=16), nullable=True),
    sa.Column('is_annotated', sa.Boolean(), nullable=True),
    sa.Column('box_count', sa.Integer(), nullable=True),
    sa.Column('create_by', sa.String(length=64), nullable=True),
    sa.Column('update_by', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('class_mapping', sa.JSON(), nullable=False),
    sa.Column('total_images', sa.Integer(), nullable=True),
    sa.Column('train_count', sa.Integer(), nullable=True),
    sa.Column('val_count', sa.Integer(), nullable=True),
    sa.Column('test_count', sa.Integer(), nullable=True),
    sa.Column('create_by', sa.String(length=64), nullable=True),
    sa.Column('update_by', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('detection_box',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('result_id', sa.BigInteger(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox_x1', sa.Float(), nullable=False),
    sa.Column('bbox_y1', sa.Float(), nullable=False),
    sa.Column('bbox_x2', sa.Float(), nullable=False),
    sa.Column('bbox_y2', sa.Float(), nullable=False),
    sa.Column('create_by', sa.String(length=64), nullable=True),
    sa.Column('update_by', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detection_box', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_box_result_id'), ['result_id'], unique=False)

    op.create_table('detection_result',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=32), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('inference_time_ms', sa.Float(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('detections_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('create_by', sa.String(length=64), nullable=True),
    sa.Column('update_by', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('create_by', sa.String(length=64), nullable=True),
    sa.Column('update_by', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stream_config',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.String(length=64), nullable=False),
    sa.Column('stream_url', sa.Text(), nullable=False),
    sa.Column('alarm_types', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('alarm_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.String(length=64), nullable=True),
    sa.Column('update_by', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stream_id')
    )
    op.create_table('sys_session',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('sys_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sys_session_user_id'), ['user_id'], unique=False)

    op.create_table('sys_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.String(length=64), nullable=True),
    sa.Column('update_by', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('system_config',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=128), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('config_type', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('create_by', sa.String(length=64), nullable=True),
    sa.Column('update_by', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('training_record',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('dataset_name', sa.String(length=128), nullable=True),
    sa.Column('epochs', sa.Integer(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('img_size', sa.Integer(), nullable=True),
    sa.Column('best_map50', sa.Float(), nullable=True),
    sa.Column('best_map50_95', sa.Float(), nullable=True),
    sa.Column('model_path', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.String(length=64), nullable=True),
    sa.Column('update_by', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_record')
    op.drop_table('system_config')
    op.drop_table('sys_user')
    with op.batch_alter_table('sys_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sys_session_user_id'))

    op.drop_table('sys_session')
    op.drop_table('stream_config')
    op.drop_table('operation_log')
    op.drop_table('detection_result')
    with op.batch_alter_table('detection_box', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_box_result_id'))

    op.drop_table('detection_box')
    op.drop_table('dataset')
    op.drop_table('annotation_image')
    with op.batch_alter_table('annotation_box', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_box_image_id'))

    op.drop_table('annotation_box')
    op.drop_table('alarm_record')
    # ### end Alembic commands ###
